services:
  - type: web
    name: ai-dashboard-gen
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: TOGETHER_API_KEY
        fromDotEnv: true
